### ISSUE TITLE
Force loading image even when not visible

### ISSUE THREAD

**Issue by idoshamun** [dinbror/blazy#110]
I want some images on my website to lazy load without even being inside the viewport.
In simple words, I want to skip `elementInView` check and force loading the image.

**Comment by dinbror** [comment]
Hi @idoshamun.
What about the public function, load(), that comes with blazy?

**Comment by idoshamun** [comment]
It is actually much easier to just pass an option instead of calling the `load` function and passing the right elements, in my opinion anyway

**Comment by dinbror** [comment]
Yes :) but how would it know which images to load or not to load outside the viewport. Will you add a specific class or are you looking after a feature like gajus is proposing?

https://github.com/dinbror/blazy/pull/104

**Comment by idoshamun** [comment]
#104 could help in other use cases.
I guess what I am aiming for is an option to pass to blazy constructor and every element in the given selector will be load without any relation to the viewport

**Comment by dinbror** [comment]
I see. But you can do that quite easy with the load function. I want to keep the script as small as possible:

```
var imagesToLoad = document.querySelectorAll('.force-lazy-load');
var blazy = new Blazy();
blazy.load(imagesToLoad);
```

**Comment by idoshamun** [comment]
I'll check this out!

**Comment by k03n00b** [comment]
I think there could be better ways than `ele.offsetWidth` to check if element is visible or not.
At least `(ele.offsetWidth > 0 && ele.offsetHeight > 0)` should be changed to `(ele.offsetWidth > 0 || ele.offsetHeight > 0)`, because then it works with visible elements where's only height.

Used multiple hours to solve why my cover image wasn't loaded and `loadInvisible` did the trick.
I have regular `div` with CSS background-image for preloading and few floating elements inside it, so offsetWidth is zero, even element is visible and real width for this element is over 600px.

**Comment by dinbror** [comment]
Hey @k03n00b 

Do you have a link. I would like to see what you have done :) 
I always reserve the space for an image or background to avoid page reflows when it lazy loads

**Comment by dinbror** [comment]
Hey @idoshamun 

Can I close this one?

**Comment by idoshamun** [comment]
Yap, if anything new pops up I'll let you know

**Comment by dinbror** [comment]
Coolio
