### ISSUE TITLE
Browser width

### ISSUE THREAD

**Issue by ivansieder** [dinbror/blazy#74]
Instead of forcing window.screen.width (for the breakpoints), add the possibility to drop this 3 options in when initializing the plugin:
- window.screen.width - Complete screen width
- document.body.offsetWidth - Width of browser window, as someone might have the browser resized and not at full width of the Monitor
- element.parentElement.offsetWidth - As not all images might be at full width (for this you might also pass along the parent when iterating over the elements)

**Comment by dinbror** [comment]
Hey @ivansieder 

So you want the possibility to control what the breakpoints should adjust against instead of always window.screen.width?
The reason why I’m looking at the screen width and not the browser width is that I don’t want to load multiple image sources for the same image when you resize (multiple server request per image). And if you have a big screen but the start width of your browser window is something small I don’t want to upscale a low res image if you resize it up.
